version: 2.1

jobs:
  save_hello_world_output:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          command: echo "text to output here" > output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt
  print_output_file:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt
workflows:
  save-hello-workflow:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
